update

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -26,6 +26,21 @@ function check_committer() {
   fi
 }
 
+function check_no_it_only() {
+  ONLY_REGEX='.only('
+  FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.ts" | tr '\n' ' ')
+  if [ -n "$FILES" ]; then
+      # Check for the ONLY_REGEX in each staged test.ts file
+      for FILE in $FILES; do
+          if grep -q "$ONLY_REGEX" "$FILE"; then
+              echo "ERROR: Found 'only.' reference in $FILE"
+              echo "Please remove 'only.' comments before committing."
+              exit 1
+          fi
+      done
+  fi
+}
+
 function build_dist() {
   yarn test
   yarn build
@@ -33,5 +48,6 @@ function build_dist() {
 }
 
 check_committer
+check_no_it_only
 check_todo
 build_dist
